name: Env Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set working directory
        run: cd ./frontend/src/main/frontend

      - name: Set environment variables for the deployment
        run: |
          if [ ${{ github.event.pull_request.base.ref }} == 'main' ]; then
            echo "REACT_APP_API_URL=https://benchscape.azurewebsites.net/" >> .env
          elif [ ${{ github.event.pull_request.base.ref }} == 'integration' ]; then
            echo "REACT_APP_API_URL=https://benchscape-integration.azurewebsites.net/" >> .env
          fi

      - name: Install dependencies and build
        run: |
          cd ./frontend/src/main/frontend
          npm install
          npm run build

      # Add your deployment steps here
